DROP TABLE IF EXISTS "user";


CREATE TABLE IF NOT EXISTS "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pseudo" text NOT NULL,
  "firstname" text NOT NULL,  
  "lastname" text NOT NULL,
  "email" text NOT NULL,
  "password" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);


DROP TABLE IF EXISTS "poll";


CREATE TABLE IF NOT EXISTS "poll" (
  "id" INT PRIMARY KEY, -- UNIQUE et NOT NULL = PRIMARY KEY (clef primaire)
  "title" text NOT NULL, 
  "question" text NOT NULL,
  "choice_a" text NOT NULL,
  "choice_b" text NOT NULL,
  "result_a" INT,
  "result_b" INT,
  "user_id" integer NOT NULL REFERENCES "user"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

